# Generated by Django 4.2.4 on 2023-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_phoneno_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="userid",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
