# Generated by Django 4.2.4 on 2023-09-29 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_userprofile_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "photo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_photos/"
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="achievement_photos/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
