# Generated by Django 4.2.4 on 2023-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_achievement_rollno"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
